[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "6KMVQWmTXpd36ryMi7i91yeLsgM6S4BiaTX3UczEkvqq"

[programs.mainnet]
crowdfunding = "6KMVQWmTXpd36ryMi7i91yeLsgM6S4BiaTX3UczEkvqq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
dev = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
