[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "6KMVQWmTXpd36ryMi7i91yeLsgM6S4BiaTX3UczEkvqq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/roster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
